### ISSUE TITLE
[Question] Whether the server can connect to multiple clients and separate control client

### ISSUE THREAD

**Issue by DYZ-H** [Apollo3zehn/FluentModbus#136]
![image](https://github.com/user-attachments/assets/5cbedfe3-9cfb-4979-83c2-6b490915aacd)
In sample code ,I can not find a way to change data with an unitIdentifier,but client will with an unitIdentifier when change data.
I wonder how server  to connect multiple clients and control client separately

**Comment by Apollo3zehn** [comment]
Instead of `var registers = server.GetHoldingRegisters();` you can write `var registers = server.GetHoldingRegisters(unitIdentifier: xxx);`

And on the server side you can create more units and control them via:

![grafik](https://github.com/user-attachments/assets/5f9caeb4-e696-42ad-b2e0-4f0989f799e1)

**Comment by DYZ-H** [comment]
Thank you very much for your reply,I have tested it ss you said，works fine。
